name: Advanced Build and Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'dist/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'dist/**'

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Check if dist folder exists and has changes
      id: dist_check
      run: |
        if [ -d "dist" ]; then
          git add dist/
          if git diff --staged --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes in dist/ folder"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in dist/ folder"
          fi
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "dist/ folder created"
        fi

    - name: Commit and push dist changes
      if: steps.dist_check.outputs.has_changes == 'true' && github.event_name == 'push'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add dist/
        git commit -m "🤖 Auto-build: Update dist/ folder [skip ci]
        
        Auto-generated from commit: ${{ github.sha }}
        Triggered by: ${{ github.actor }}"
        
        # Try to push, handle potential conflicts
        max_retries=3
        retry_count=0
        
        while [ $retry_count -lt $max_retries ]; do
          if git push; then
            echo "Successfully pushed changes"
            break
          else
            echo "Push failed, attempting to pull and rebase... (attempt $((retry_count + 1)))"
            git pull --rebase origin main
            retry_count=$((retry_count + 1))
            
            if [ $retry_count -eq $max_retries ]; then
              echo "Failed to push after $max_retries attempts"
              exit 1
            fi
          fi
        done

    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request' && steps.dist_check.outputs.has_changes == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🤖 **Build Info**: This PR would update the `dist/` folder when merged. The build completed successfully!'
          });
